Improve error message

diff --git a/.github/workflows/fix-linting.yml b/.github/workflows/fix-linting.yml
--- a/.github/workflows/fix-linting.yml
+++ b/.github/workflows/fix-linting.yml
@@ -41,9 +41,13 @@ jobs:
 
           # Verify that the commit sha matches what we expect, just in
           # case a new commit was pushed after the workflow was triggered.
-          [[ $(git log -1 --format=%H) == ${{ steps.branch-deploy.outputs.sha }} ]] || exit 1
+          if [[ $(git log -1 --format=%H) != $EXPECTED_SHA ]]; then
+             echo "::error title=bad-commit-id::Expected: $EXPECTED_SHA Actual: $(git log -1 --format=%H)"
+             exit 1
+          fi
         env:
           GITHUB_TOKEN: ${{ secrets.nf_core_bot_auth_token }}
+          EXPECTED_SHA: ${{ needs.prepare-matrix.outputs.sha }}
 
       # Install and run prek
       - name: Run prek
diff --git a/.github/workflows/update-template-snapshots.yml b/.github/workflows/update-template-snapshots.yml
--- a/.github/workflows/update-template-snapshots.yml
+++ b/.github/workflows/update-template-snapshots.yml
@@ -170,9 +170,13 @@ jobs:
 
           # Verify that the commit sha matches what we expect, just in
           # case a new commit was pushed after the workflow was triggered.
-          [[ $(git log -1 --format=%H) == ${{ needs.prepare-matrix.outputs.sha }} ]] || exit 1
+          if [[ $(git log -1 --format=%H) != $EXPECTED_SHA ]]; then
+             echo "::error title=bad-commit-id::Expected: $EXPECTED_SHA Actual: $(git log -1 --format=%H)"
+             exit 1
+          fi
         env:
           GITHUB_TOKEN: ${{ secrets.nf_core_bot_auth_token }}
+          EXPECTED_SHA: ${{ needs.prepare-matrix.outputs.sha }}
 
       - name: Download all snapshot artifacts
         uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
